name: Generate test matrices pages

# Controls when the action will run.
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 4 * * *'
jobs:
  generate-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Generate matrix-benchmark 'results' files ğŸ”§
        run: |
          cd submodules/ci-dashboard/
          make matrix_benchmarks

      - name: Generate matrix-benchmark plots ğŸ”§
        run: |
          mkdir results

          ln -s ../submodules/ci-dashboard/output/matrix_benchmarks results/nightly

          make matrix_benchmarks

          ./visualize "__generate__=operator-version=1.6.2&@finish-date=<all>&stats=Nightly Ansible Tasks Ok&stats=Nightly Step Count&settings-order=expe|benchmark|operator-version|openshift-version|instance-type|@finish-date"

          mkdir output
          mv fig* output/
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: output # The folder the action should deploy.
